.TH "TagManager.testSub" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.testSub
.SH SYNOPSIS
.br
.PP
.PP
Inherits Autodesk\&.Max\&.Plugins\&.UtilityObj\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDescriptor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestSub\fP (\fBDescriptor\fP descriptor)"
.br
.ti -1c
.RI "override void \fBBeginEditParams\fP (IInterface ip, IIUtil iu)"
.br
.ti -1c
.RI "override void \fBEndEditParams\fP (IInterface ip, IIUtil iu)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB40\fP of file \fBTagManager\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.testSub\&.testSub (\fBDescriptor\fP descriptor)"

.PP
Definition at line \fB90\fP of file \fBTagManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TagManager\&.testSub\&.BeginEditParams (IInterface ip, IIUtil iu)"

.PP
Definition at line \fB95\fP of file \fBTagManager\&.cs\fP\&.
.SS "override void TagManager\&.testSub\&.EndEditParams (IInterface ip, IIUtil iu)"

.PP
Definition at line \fB100\fP of file \fBTagManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
