.TH "TagManager.Actions.FastTag" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.Actions.FastTag
.SH SYNOPSIS
.br
.PP
.PP
Inherits CuiActionCommandAdapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (object parameter)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBCategory\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalCategory\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TagManager\&.Actions\&.FastTag\&.Execute (object parameter)"

.PP
Definition at line \fB79\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string TagManager\&.Actions\&.FastTag\&.ActionText\fC [get]\fP"

.PP
Definition at line \fB51\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.Actions\&.FastTag\&.Category\fC [get]\fP"

.PP
Definition at line \fB58\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.Actions\&.FastTag\&.InternalActionText\fC [get]\fP"

.PP
Definition at line \fB65\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.Actions\&.FastTag\&.InternalCategory\fC [get]\fP"

.PP
Definition at line \fB72\fP of file \fBTagCenterAction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
