.TH "TagManager.FastWPFTag" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.FastWPFTag
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Controls\&.UserControl, and IComponentConnector\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateAutoCompleteSource\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Window \fBwinParent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBFastWPFTag\&.xaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.FastWPFTag\&.FastWPFTag ()"

.PP
Definition at line \fB29\fP of file \fBFastWPFTag\&.xaml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TagManager\&.FastWPFTag\&.CreateAutoCompleteSource ()"

.PP
Definition at line \fB36\fP of file \fBFastWPFTag\&.xaml\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Window TagManager\&.FastWPFTag\&.winParent"

.PP
Definition at line \fB27\fP of file \fBFastWPFTag\&.xaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
