.TH "TagManager.ConsoleElement" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.ConsoleElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTagManager\&.IConsoleSelElement\fP, and ISerializable\&.
.PP
Inherited by \fBTagManager\&.ConsoleContainerElement\fP, and \fBTagManager\&.ConsoleStringSelElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract List< uint > \fBgetCorrespondingSel\fP ()"
.br
.ti -1c
.RI "abstract string \fBgetCorrespondingStr\fP ()"
.br
.ti -1c
.RI "void \fBGetObjectData\fP (SerializationInfo info, StreamingContext context)"
.br
.in -1c
.in +1c
.ti -1c
.RI "List< uint > \fBgetCorrespondingSel\fP ()"
.br
.ti -1c
.RI "string \fBgetCorrespondingStr\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static List< uint > \fBoperator+\fP (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator+\fP (List< uint > c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator\-\fP (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator\-\fP (List< uint > c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator*\fP (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator*\fP (List< uint > c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator/\fP (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator/\fP (List< uint > c1, \fBConsoleElement\fP c2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBConsoleElement\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.ConsoleElement\&.ConsoleElement ()"

.PP
Definition at line \fB29\fP of file \fBConsoleElement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract List< uint > TagManager\&.ConsoleElement\&.getCorrespondingSel ()\fC [pure virtual]\fP"

.PP
Implements \fBTagManager\&.IConsoleSelElement\fP\&.
.SS "abstract string TagManager\&.ConsoleElement\&.getCorrespondingStr ()\fC [pure virtual]\fP"

.PP
Implements \fBTagManager\&.IConsoleSelElement\fP\&.
.SS "void TagManager\&.ConsoleElement\&.GetObjectData (SerializationInfo info, StreamingContext context)"

.PP
Definition at line \fB93\fP of file \fBConsoleElement\&.cs\fP\&.
.SS "static List< uint > TagManager\&.ConsoleElement\&.operator* (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)\fC [static]\fP"

.PP
Definition at line \fB68\fP of file \fBConsoleElement\&.cs\fP\&.
.SS "static List< uint > TagManager\&.ConsoleElement\&.operator* (List< uint > c1, \fBConsoleElement\fP c2)\fC [static]\fP"

.PP
Definition at line \fB74\fP of file \fBConsoleElement\&.cs\fP\&.
.SS "static List< uint > TagManager\&.ConsoleElement\&.operator+ (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)\fC [static]\fP"

.PP
Definition at line \fB38\fP of file \fBConsoleElement\&.cs\fP\&.
.SS "static List< uint > TagManager\&.ConsoleElement\&.operator+ (List< uint > c1, \fBConsoleElement\fP c2)\fC [static]\fP"

.PP
Definition at line \fB46\fP of file \fBConsoleElement\&.cs\fP\&.
.SS "static List< uint > TagManager\&.ConsoleElement\&.operator\- (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)\fC [static]\fP"

.PP
Definition at line \fB54\fP of file \fBConsoleElement\&.cs\fP\&.
.SS "static List< uint > TagManager\&.ConsoleElement\&.operator\- (List< uint > c1, \fBConsoleElement\fP c2)\fC [static]\fP"

.PP
Definition at line \fB61\fP of file \fBConsoleElement\&.cs\fP\&.
.SS "static List< uint > TagManager\&.ConsoleElement\&.operator/ (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)\fC [static]\fP"

.PP
Definition at line \fB80\fP of file \fBConsoleElement\&.cs\fP\&.
.SS "static List< uint > TagManager\&.ConsoleElement\&.operator/ (List< uint > c1, \fBConsoleElement\fP c2)\fC [static]\fP"

.PP
Definition at line \fB86\fP of file \fBConsoleElement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
