.TH "TagManager.IConsoleSelElement" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.IConsoleSelElement
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTagManager\&.ConsoleElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< uint > \fBgetCorrespondingSel\fP ()"
.br
.ti -1c
.RI "string \fBgetCorrespondingStr\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBIConsoleSelElement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
