.TH "TagManager.ActionRegister" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.ActionRegister
.SH SYNOPSIS
.br
.PP
.PP
Inherits CuiActionCommandAdapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (object param)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBCategory\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalCategory\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBActionRegister\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TagManager\&.ActionRegister\&.Execute (object param)"

.PP
Definition at line \fB35\fP of file \fBActionRegister\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string TagManager\&.ActionRegister\&.ActionText\fC [get]\fP"

.PP
Definition at line \fB7\fP of file \fBActionRegister\&.cs\fP\&.
.SS "override string TagManager\&.ActionRegister\&.Category\fC [get]\fP"

.PP
Definition at line \fB14\fP of file \fBActionRegister\&.cs\fP\&.
.SS "override string TagManager\&.ActionRegister\&.InternalActionText\fC [get]\fP"

.PP
Definition at line \fB21\fP of file \fBActionRegister\&.cs\fP\&.
.SS "override string TagManager\&.ActionRegister\&.InternalCategory\fC [get]\fP"

.PP
Definition at line \fB28\fP of file \fBActionRegister\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
