.TH "TagManager.TagCenter.Descriptor" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.TagCenter.Descriptor
.SH SYNOPSIS
.br
.PP
.PP
Inherits Autodesk\&.Max\&.Plugins\&.ClassDesc2\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPostLoadCallback\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDescriptor\fP (IGlobal global)"
.br
.ti -1c
.RI "override object \fBCreate\fP (bool loading)"
.br
.ti -1c
.RI "override IOResult \fBSave\fP (IISave isave)"
.br
.ti -1c
.RI "override IOResult \fBLoad\fP (IILoad iload)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBsaveIsNeeded\fP = true"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static IClass_ID \fB_classID\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "IGlobal \fB_global\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IGlobal \fBGlobal\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBCategory\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IClass_ID \fBClassID\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBClassName\fP\fC [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsPublic\fP\fC [get]\fP"
.br
.ti -1c
.RI "override SClass_ID \fBSuperClassID\fP\fC [get]\fP"
.br
.ti -1c
.RI "override bool \fBNeedsToSave\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBNonLocalizedClassName\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB54\fP of file \fBTagCenter\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.TagCenter\&.Descriptor\&.Descriptor (IGlobal global)"

.PP
Definition at line \fB109\fP of file \fBTagCenter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override object TagManager\&.TagCenter\&.Descriptor\&.Create (bool loading)"

.PP
Definition at line \fB132\fP of file \fBTagCenter\&.cs\fP\&.
.SS "override IOResult TagManager\&.TagCenter\&.Descriptor\&.Load (IILoad iload)"

.PP
Definition at line \fB161\fP of file \fBTagCenter\&.cs\fP\&.
.SS "override IOResult TagManager\&.TagCenter\&.Descriptor\&.Save (IISave isave)"

.PP
Definition at line \fB156\fP of file \fBTagCenter\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "IClass_ID TagManager\&.TagCenter\&.Descriptor\&._classID\fC [static]\fP"

.PP
Definition at line \fB102\fP of file \fBTagCenter\&.cs\fP\&.
.SS "IGlobal TagManager\&.TagCenter\&.Descriptor\&._global\fC [protected]\fP"

.PP
Definition at line \fB101\fP of file \fBTagCenter\&.cs\fP\&.
.SS "bool TagManager\&.TagCenter\&.Descriptor\&.saveIsNeeded = true"

.PP
Definition at line \fB103\fP of file \fBTagCenter\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string TagManager\&.TagCenter\&.Descriptor\&.Category\fC [get]\fP"

.PP
Definition at line \fB117\fP of file \fBTagCenter\&.cs\fP\&.
.SS "override IClass_ID TagManager\&.TagCenter\&.Descriptor\&.ClassID\fC [get]\fP"

.PP
Definition at line \fB122\fP of file \fBTagCenter\&.cs\fP\&.
.SS "override string TagManager\&.TagCenter\&.Descriptor\&.ClassName\fC [get]\fP"

.PP
Definition at line \fB127\fP of file \fBTagCenter\&.cs\fP\&.
.SS "IGlobal TagManager\&.TagCenter\&.Descriptor\&.Global\fC [get]\fP"

.PP
Definition at line \fB105\fP of file \fBTagCenter\&.cs\fP\&.
.SS "override bool TagManager\&.TagCenter\&.Descriptor\&.IsPublic\fC [get]\fP"

.PP
Definition at line \fB137\fP of file \fBTagCenter\&.cs\fP\&.
.SS "override bool TagManager\&.TagCenter\&.Descriptor\&.NeedsToSave\fC [get]\fP"

.PP
Definition at line \fB146\fP of file \fBTagCenter\&.cs\fP\&.
.SS "override string TagManager\&.TagCenter\&.Descriptor\&.NonLocalizedClassName\fC [get]\fP"

.PP
Definition at line \fB154\fP of file \fBTagCenter\&.cs\fP\&.
.SS "override SClass_ID TagManager\&.TagCenter\&.Descriptor\&.SuperClassID\fC [get]\fP"

.PP
Definition at line \fB142\fP of file \fBTagCenter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
