.TH "TagManager.TagReferenceMaker" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.TagReferenceMaker
.SH SYNOPSIS
.br
.PP
.PP
Inherits ReferenceMaker\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTagReferenceMaker\fP (\fBTagCenter\fP _parent)"
.br
.ti -1c
.RI "override RefResult \fBNotifyRefChanged\fP (IInterval changeInt, IReferenceTarget hTarget, ref UIntPtr partID, RefMessage message)"
.br
.ti -1c
.RI "override IOResult \fBSave\fP (IISave isave)"
.br
.ti -1c
.RI "override IOResult \fBLoad\fP (IILoad iload)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBremember\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBTagReferenceMaker\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.TagReferenceMaker\&.TagReferenceMaker (\fBTagCenter\fP _parent)"

.PP
Definition at line \fB15\fP of file \fBTagReferenceMaker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override IOResult TagManager\&.TagReferenceMaker\&.Load (IILoad iload)"

.PP
Definition at line \fB29\fP of file \fBTagReferenceMaker\&.cs\fP\&.
.SS "override RefResult TagManager\&.TagReferenceMaker\&.NotifyRefChanged (IInterval changeInt, IReferenceTarget hTarget, ref UIntPtr partID, RefMessage message)"

.PP
Definition at line \fB20\fP of file \fBTagReferenceMaker\&.cs\fP\&.
.SS "override IOResult TagManager\&.TagReferenceMaker\&.Save (IISave isave)"

.PP
Definition at line \fB24\fP of file \fBTagReferenceMaker\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string TagManager\&.TagReferenceMaker\&.remember = ''"

.PP
Definition at line \fB13\fP of file \fBTagReferenceMaker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
