.TH "TagManager" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssemblyFunctions\fP"
.br
.ti -1c
.RI "class \fBConsoleContainerElement\fP"
.br
.ti -1c
.RI "class \fBConsoleElement\fP"
.br
.ti -1c
.RI "class \fBConsoleStringSelElement\fP"
.br
.ti -1c
.RI "class \fBCustomExtension\fP"
.br
.ti -1c
.RI "class \fBDDNode\fP"
.br
.RI "DDNode is a tree-like container base, it handles hierarchy changes\&. "
.ti -1c
.RI "class \fBDependencyObjExtensions\fP"
.br
.ti -1c
.RI "class \fBEditableTextBlock\fP"
.br
.RI "Interaction logic for EditableTextBlock\&.xaml\&. "
.ti -1c
.RI "class \fBEnumHelper\fP"
.br
.ti -1c
.RI "class \fBFastWPFTag\fP"
.br
.ti -1c
.RI "interface \fBIConsoleSelElement\fP"
.br
.ti -1c
.RI "class \fBItemToContextMenuConverter\fP"
.br
.ti -1c
.RI "class \fBLayerManager\fP"
.br
.ti -1c
.RI "class \fBMaxPluginUtilities\fP"
.br
.ti -1c
.RI "class \fBNodesToBoolConverter\fP"
.br
.ti -1c
.RI "class \fBObjectDataChunk\fP"
.br
.ti -1c
.RI "class \fBObjectDataChunkExtensions\fP"
.br
.ti -1c
.RI "class \fBSortableObservableCollection\fP"
.br
.RI "Represents a dynamic data collection that provides notifications when items get added, removed, or when the whole list is refreshed and allows sorting\&. "
.ti -1c
.RI "class \fBSortableObservableCollectionExtension\fP"
.br
.ti -1c
.RI "class \fBTagCenter\fP"
.br
.ti -1c
.RI "class \fBTagGlobals\fP"
.br
.ti -1c
.RI "class \fBTagHelperMethods\fP"
.br
.ti -1c
.RI "class \fBTagMethods\fP"
.br
.ti -1c
.RI "class \fBTagNode\fP"
.br
.RI "TagNode is the container for entities it inehrites from DDNode\&. "
.ti -1c
.RI "class \fBTagReferenceMaker\fP"
.br
.ti -1c
.RI "class \fBWindowExtensions\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBconcat\fP { \fBaddition\fP, \fBsubstraction\fP, \fBintersection\fP, \fBexcept\fP }"
.br
.ti -1c
.RI "enum \fBConsoleElementModifier\fP { \fBNone\fP, \fBSelection\fP, \fBContaining\fP, \fBChildren\fP, \fBNot\fP, \fBVisible\fP }"
.br
.ti -1c
.RI "enum \fBEntityVisibility\fP { \fBVsible\fP, \fBHidden\fP, \fBMixed\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum TagManager\&.concat"

.PP
Definition at line \fB13\fP of file \fBConsoleElement\&.cs\fP\&.
.SS "enum TagManager\&.ConsoleElementModifier"

.PP
Definition at line \fB12\fP of file \fBConsoleStringSelElement\&.cs\fP\&.
.SS "enum TagManager\&.EntityVisibility"

.PP
Definition at line \fB9\fP of file \fBEntityVisibility\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
