.TH "TagManager.Actions" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.Actions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplyEntityFromLayer\fP"
.br
.ti -1c
.RI "class \fBApplyLastEntity\fP"
.br
.ti -1c
.RI "class \fBContainingEntity\fP"
.br
.ti -1c
.RI "class \fBContainingEntityGrow\fP"
.br
.ti -1c
.RI "class \fBContainingEntityShrink\fP"
.br
.ti -1c
.RI "class \fBCopyEntity\fP"
.br
.ti -1c
.RI "class \fBCreateSelectionSet\fP"
.br
.ti -1c
.RI "class \fBFastTag\fP"
.br
.ti -1c
.RI "class \fBOpenClose\fP"
.br
.ti -1c
.RI "class \fBRemoveObjectsFromEntities\fP"
.br
.ti -1c
.RI "class \fBToggleAutoCloneTag\fP"
.br
.ti -1c
.RI "class \fBToggleAutoRename\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
