.TH "TagManager.ObjectDataChunk" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.ObjectDataChunk
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectDataChunk\fP (List< \fBTagNode\fP > _entities)"
.br
.ti -1c
.RI "\fBObjectDataChunk\fP (List< Guid > list)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBObjectDataChunk\fP \fBByteArrayToObjectDataChunk\fP (byte[] arrBytes)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< string > \fBentitiesIDs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBObjectDataChunk\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.ObjectDataChunk\&.ObjectDataChunk (List< \fBTagNode\fP > _entities)"

.PP
Definition at line \fB15\fP of file \fBObjectDataChunk\&.cs\fP\&.
.SS "TagManager\&.ObjectDataChunk\&.ObjectDataChunk (List< Guid > list)"

.PP
Definition at line \fB24\fP of file \fBObjectDataChunk\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBObjectDataChunk\fP TagManager\&.ObjectDataChunk\&.ByteArrayToObjectDataChunk (byte[] arrBytes)\fC [static]\fP"

.PP
Definition at line \fB30\fP of file \fBObjectDataChunk\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<string> TagManager\&.ObjectDataChunk\&.entitiesIDs"

.PP
Definition at line \fB13\fP of file \fBObjectDataChunk\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
