.TH "TagManager.RemoveObjectsFromEntities" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.RemoveObjectsFromEntities
.SH SYNOPSIS
.br
.PP
.PP
Inherits CuiActionCommandAdapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (object parameter)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBCategory\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalCategory\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB217\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TagManager\&.RemoveObjectsFromEntities\&.Execute (object parameter)"

.PP
Definition at line \fB247\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string TagManager\&.RemoveObjectsFromEntities\&.ActionText\fC [get]\fP"

.PP
Definition at line \fB219\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.RemoveObjectsFromEntities\&.Category\fC [get]\fP"

.PP
Definition at line \fB226\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.RemoveObjectsFromEntities\&.InternalActionText\fC [get]\fP"

.PP
Definition at line \fB233\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.RemoveObjectsFromEntities\&.InternalCategory\fC [get]\fP"

.PP
Definition at line \fB240\fP of file \fBTagCenterAction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
