.TH "TagManager.NodesToBoolConverter" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.NodesToBoolConverter
.SH SYNOPSIS
.br
.PP
.PP
Inherits MarkupExtension, and IMultiValueConverter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override object \fBProvideValue\fP (IServiceProvider serviceProvider)"
.br
.ti -1c
.RI "object \fBConvert\fP (object[] values, Type targetType, object parameter, CultureInfo culture)"
.br
.ti -1c
.RI "object[] \fBConvertBack\fP (object value, Type[] targetTypes, object parameter, System\&.Globalization\&.CultureInfo culture)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBNodesToBoolConverter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "object TagManager\&.NodesToBoolConverter\&.Convert (object[] values, Type targetType, object parameter, CultureInfo culture)"

.PP
Definition at line \fB27\fP of file \fBNodesToBoolConverter\&.cs\fP\&.
.SS "object[] TagManager\&.NodesToBoolConverter\&.ConvertBack (object value, Type[] targetTypes, object parameter, System::Globalization::CultureInfo culture)"

.PP
Definition at line \fB42\fP of file \fBNodesToBoolConverter\&.cs\fP\&.
.SS "override object TagManager\&.NodesToBoolConverter\&.ProvideValue (IServiceProvider serviceProvider)"

.PP
Definition at line \fB18\fP of file \fBNodesToBoolConverter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
