.TH "TagManager.TagManager" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.TagManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBManage\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IGlobal \fBmaxGlobal\fP"
.br
.ti -1c
.RI "IInterface13 \fBmaxInterface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBTagManager\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.TagManager\&.TagManager ()"

.PP
Definition at line \fB18\fP of file \fBTagManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void TagManager\&.TagManager\&.Manage ()\fC [static]\fP"

.PP
Definition at line \fB24\fP of file \fBTagManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "IGlobal TagManager\&.TagManager\&.maxGlobal"

.PP
Definition at line \fB15\fP of file \fBTagManager\&.cs\fP\&.
.SS "IInterface13 TagManager\&.TagManager\&.maxInterface"

.PP
Definition at line \fB16\fP of file \fBTagManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
