.TH "TagManager.testSub.Descriptor" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.testSub.Descriptor
.SH SYNOPSIS
.br
.PP
.PP
Inherits Autodesk\&.Max\&.Plugins\&.ClassDesc2\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDescriptor\fP (IGlobal global)"
.br
.ti -1c
.RI "override object \fBCreate\fP (bool loading)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "IGlobal \fB_global\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IGlobal \fBGlobal\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBCategory\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IClass_ID \fBClassID\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBClassName\fP\fC [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsPublic\fP\fC [get]\fP"
.br
.ti -1c
.RI "override SClass_ID \fBSuperClassID\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB42\fP of file \fBTagManager\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.testSub\&.Descriptor\&.Descriptor (IGlobal global)"

.PP
Definition at line \fB52\fP of file \fBTagManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override object TagManager\&.testSub\&.Descriptor\&.Create (bool loading)"

.PP
Definition at line \fB73\fP of file \fBTagManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "IGlobal TagManager\&.testSub\&.Descriptor\&._global\fC [protected]\fP"

.PP
Definition at line \fB44\fP of file \fBTagManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string TagManager\&.testSub\&.Descriptor\&.Category\fC [get]\fP"

.PP
Definition at line \fB58\fP of file \fBTagManager\&.cs\fP\&.
.SS "override IClass_ID TagManager\&.testSub\&.Descriptor\&.ClassID\fC [get]\fP"

.PP
Definition at line \fB63\fP of file \fBTagManager\&.cs\fP\&.
.SS "override string TagManager\&.testSub\&.Descriptor\&.ClassName\fC [get]\fP"

.PP
Definition at line \fB68\fP of file \fBTagManager\&.cs\fP\&.
.SS "IGlobal TagManager\&.testSub\&.Descriptor\&.Global\fC [get]\fP"

.PP
Definition at line \fB47\fP of file \fBTagManager\&.cs\fP\&.
.SS "override bool TagManager\&.testSub\&.Descriptor\&.IsPublic\fC [get]\fP"

.PP
Definition at line \fB78\fP of file \fBTagManager\&.cs\fP\&.
.SS "override SClass_ID TagManager\&.testSub\&.Descriptor\&.SuperClassID\fC [get]\fP"

.PP
Definition at line \fB83\fP of file \fBTagManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
