.TH "TagManager.ItemToContextMenuConverter" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.ItemToContextMenuConverter
.SH SYNOPSIS
.br
.PP
.PP
Inherits IValueConverter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBConvert\fP (object value, Type targetType, object parameter, CultureInfo culture)"
.br
.ti -1c
.RI "object \fBConvertBack\fP (object value, Type targetType, object parameter, CultureInfo culture)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static ContextMenu \fBStdContextMenu\fP"
.br
.ti -1c
.RI "static ContextMenu \fBRootContextMenu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBItemToContextMenuConverter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "object TagManager\&.ItemToContextMenuConverter\&.Convert (object value, Type targetType, object parameter, CultureInfo culture)"

.PP
Definition at line \fB19\fP of file \fBItemToContextMenuConverter\&.cs\fP\&.
.SS "object TagManager\&.ItemToContextMenuConverter\&.ConvertBack (object value, Type targetType, object parameter, CultureInfo culture)"

.PP
Definition at line \fB33\fP of file \fBItemToContextMenuConverter\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ContextMenu TagManager\&.ItemToContextMenuConverter\&.RootContextMenu\fC [static]\fP"

.PP
Definition at line \fB17\fP of file \fBItemToContextMenuConverter\&.cs\fP\&.
.SS "ContextMenu TagManager\&.ItemToContextMenuConverter\&.StdContextMenu\fC [static]\fP"

.PP
Definition at line \fB16\fP of file \fBItemToContextMenuConverter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
