.TH "TagManager.Actions.OpenClose" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.Actions.OpenClose
.SH SYNOPSIS
.br
.PP
.PP
Inherits CuiActionCommandAdapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (object parameter)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBCategory\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalCategory\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TagManager\&.Actions\&.OpenClose\&.Execute (object parameter)"

.PP
Definition at line \fB37\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string TagManager\&.Actions\&.OpenClose\&.ActionText\fC [get]\fP"

.PP
Definition at line \fB9\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.Actions\&.OpenClose\&.Category\fC [get]\fP"

.PP
Definition at line \fB16\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.Actions\&.OpenClose\&.InternalActionText\fC [get]\fP"

.PP
Definition at line \fB23\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.Actions\&.OpenClose\&.InternalCategory\fC [get]\fP"

.PP
Definition at line \fB30\fP of file \fBTagCenterAction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
