.TH "TagManager.TagCenter" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.TagCenter
.SH SYNOPSIS
.br
.PP
.PP
Inherits ReferenceMaker, and IPlugin\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDescriptor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTagCenter\fP (\fBDescriptor\fP descriptor)"
.br
.ti -1c
.RI "void \fBCleanup\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (IGlobal global, System\&.ComponentModel\&.ISynchronizeInvoke sync)"
.br
.ti -1c
.RI "void \fBInitializeTree\fP ()"
.br
.ti -1c
.RI "void \fBCreateTagManagerWin\fP ()"
.br
.ti -1c
.RI "void \fBCreateFastTagWin\fP ()"
.br
.ti -1c
.RI "override RefResult \fBNotifyRefChanged\fP (IInterval changeInt, IReferenceTarget hTarget, ref UIntPtr partID, RefMessage message, bool propagate)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDescriptor\fP \fB_descriptor\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "EntityPan \fBfastPan\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFastWPFTag\fP \fBfastTag\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "System\&.ComponentModel\&.ISynchronizeInvoke \fBSync\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBTagCenter\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBTagCenter\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.TagCenter\&.TagCenter ()"

.PP
Definition at line \fB197\fP of file \fBTagCenter\&.cs\fP\&.
.SS "TagManager\&.TagCenter\&.TagCenter (\fBDescriptor\fP descriptor)"

.PP
Definition at line \fB200\fP of file \fBTagCenter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TagManager\&.TagCenter\&.Cleanup ()"

.PP
Definition at line \fB237\fP of file \fBTagCenter\&.cs\fP\&.
.SS "void TagManager\&.TagCenter\&.CreateFastTagWin ()"

.PP
Definition at line \fB497\fP of file \fBTagCenter\&.cs\fP\&.
.SS "void TagManager\&.TagCenter\&.CreateTagManagerWin ()"

.PP
Definition at line \fB404\fP of file \fBTagCenter\&.cs\fP\&.
.SS "void TagManager\&.TagCenter\&.Initialize (IGlobal global, System::ComponentModel::ISynchronizeInvoke sync)"

.PP
Definition at line \fB242\fP of file \fBTagCenter\&.cs\fP\&.
.SS "void TagManager\&.TagCenter\&.InitializeTree ()"

.PP
Definition at line \fB272\fP of file \fBTagCenter\&.cs\fP\&.
.SS "override RefResult TagManager\&.TagCenter\&.NotifyRefChanged (IInterval changeInt, IReferenceTarget hTarget, ref UIntPtr partID, RefMessage message, bool propagate)"

.PP
Definition at line \fB539\fP of file \fBTagCenter\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDescriptor\fP TagManager\&.TagCenter\&._descriptor"

.PP
Definition at line \fB196\fP of file \fBTagCenter\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "EntityPan TagManager\&.TagCenter\&.fastPan\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB40\fP of file \fBTagCenter\&.cs\fP\&.
.SS "\fBFastWPFTag\fP TagManager\&.TagCenter\&.fastTag\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB48\fP of file \fBTagCenter\&.cs\fP\&.
.SS "\fBTagCenter\fP TagManager\&.TagCenter\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB209\fP of file \fBTagCenter\&.cs\fP\&.
.SS "System\&.ComponentModel\&.ISynchronizeInvoke TagManager\&.TagCenter\&.Sync\fC [get]\fP"

.PP
Definition at line \fB204\fP of file \fBTagCenter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
