.TH "TagManager.CreateSelectionSet" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.CreateSelectionSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits CuiActionCommandAdapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (object parameter)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBCategory\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalCategory\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB301\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TagManager\&.CreateSelectionSet\&.Execute (object parameter)"

.PP
Definition at line \fB331\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string TagManager\&.CreateSelectionSet\&.ActionText\fC [get]\fP"

.PP
Definition at line \fB303\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.CreateSelectionSet\&.Category\fC [get]\fP"

.PP
Definition at line \fB310\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.CreateSelectionSet\&.InternalActionText\fC [get]\fP"

.PP
Definition at line \fB317\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.CreateSelectionSet\&.InternalCategory\fC [get]\fP"

.PP
Definition at line \fB324\fP of file \fBTagCenterAction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
