.TH "TagManager.ConsoleStringSelElement" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.ConsoleStringSelElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTagManager\&.ConsoleElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsoleStringSelElement\fP (string _name, ConsoleElementModifier _modifier)"
.br
.ti -1c
.RI "override List< uint > \fBgetCorrespondingSel\fP ()"
.br
.ti -1c
.RI "override string \fBgetCorrespondingStr\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBTagManager\&.ConsoleElement\fP
.in +1c
.ti -1c
.RI "abstract List< uint > \fBgetCorrespondingSel\fP ()"
.br
.ti -1c
.RI "abstract string \fBgetCorrespondingStr\fP ()"
.br
.ti -1c
.RI "void \fBGetObjectData\fP (SerializationInfo info, StreamingContext context)"
.br
.in -1c
.in +1c
.ti -1c
.RI "List< uint > \fBgetCorrespondingSel\fP ()"
.br
.ti -1c
.RI "string \fBgetCorrespondingStr\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "ConsoleElementModifier \fBmodifier\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBConsoleStringSelElement\fP (SerializationInfo info, StreamingContext context)"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBTagManager\&.ConsoleElement\fP
.in +1c
.ti -1c
.RI "static List< uint > \fBoperator+\fP (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator+\fP (List< uint > c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator\-\fP (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator\-\fP (List< uint > c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator*\fP (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator*\fP (List< uint > c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator/\fP (\fBConsoleElement\fP c1, \fBConsoleElement\fP c2)"
.br
.ti -1c
.RI "static List< uint > \fBoperator/\fP (List< uint > c1, \fBConsoleElement\fP c2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBConsoleStringSelElement\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagManager\&.ConsoleStringSelElement\&.ConsoleStringSelElement (string _name, ConsoleElementModifier _modifier)"

.PP
Definition at line \fB28\fP of file \fBConsoleStringSelElement\&.cs\fP\&.
.SS "TagManager\&.ConsoleStringSelElement\&.ConsoleStringSelElement (SerializationInfo info, StreamingContext context)\fC [protected]\fP"

.PP
Definition at line \fB84\fP of file \fBConsoleStringSelElement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override List< uint > TagManager\&.ConsoleStringSelElement\&.getCorrespondingSel ()\fC [virtual]\fP"

.PP
Implements \fBTagManager\&.ConsoleElement\fP\&.
.PP
Definition at line \fB34\fP of file \fBConsoleStringSelElement\&.cs\fP\&.
.SS "override string TagManager\&.ConsoleStringSelElement\&.getCorrespondingStr ()\fC [virtual]\fP"

.PP
Implements \fBTagManager\&.ConsoleElement\fP\&.
.PP
Definition at line \fB80\fP of file \fBConsoleStringSelElement\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ConsoleElementModifier TagManager\&.ConsoleStringSelElement\&.modifier"

.PP
Definition at line \fB26\fP of file \fBConsoleStringSelElement\&.cs\fP\&.
.SS "string TagManager\&.ConsoleStringSelElement\&.name"

.PP
Definition at line \fB25\fP of file \fBConsoleStringSelElement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
