.TH "TagManager.Actions.ContainingEntityGrow" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagManager.Actions.ContainingEntityGrow
.SH SYNOPSIS
.br
.PP
.PP
Inherits CuiActionCommandAdapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP (object parameter)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBCategory\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalActionText\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInternalCategory\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB133\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TagManager\&.Actions\&.ContainingEntityGrow\&.Execute (object parameter)"

.PP
Definition at line \fB163\fP of file \fBTagCenterAction\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string TagManager\&.Actions\&.ContainingEntityGrow\&.ActionText\fC [get]\fP"

.PP
Definition at line \fB135\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.Actions\&.ContainingEntityGrow\&.Category\fC [get]\fP"

.PP
Definition at line \fB142\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.Actions\&.ContainingEntityGrow\&.InternalActionText\fC [get]\fP"

.PP
Definition at line \fB149\fP of file \fBTagCenterAction\&.cs\fP\&.
.SS "override string TagManager\&.Actions\&.ContainingEntityGrow\&.InternalCategory\fC [get]\fP"

.PP
Definition at line \fB156\fP of file \fBTagCenterAction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
