.TH "TagPan" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagPan
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFastHost\fP"
.br
.ti -1c
.RI "class \fBObservableCollection\fP"
.br
.RI "Represents a dynamic data collection that provides notifications when items get added, removed, or when the whole list is refreshed\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
