.TH "TagPan.FastHost" 3TagManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagPan.FastHost
.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateAutoCompleteSource\fP (TagPanel _tagPan)"
.br
.ti -1c
.RI "void \fBLinkParent\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "System\&.EventHandler \fBForceRedraw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBFastHost\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TagPan\&.FastHost\&.FastHost ()"

.PP
Definition at line \fB14\fP of file \fBFastHost\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TagPan\&.FastHost\&.CreateAutoCompleteSource (TagPanel _tagPan)"

.PP
Definition at line \fB22\fP of file \fBFastHost\&.cs\fP\&.
.SS "override void TagPan\&.FastHost\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Definition at line \fB30\fP of file \fBFastHost\&.cs\fP\&.
.SS "void TagPan\&.FastHost\&.LinkParent ()"

.PP
Definition at line \fB26\fP of file \fBFastHost\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "System\&.EventHandler TagPan\&.FastHost\&.ForceRedraw"

.PP
Definition at line \fB13\fP of file \fBFastHost\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TagManager from the source code\&.
